adventureworks:
  target: clickhouse
  outputs:
    duckdb:
     type: duckdb
     path: target/adventureworks.duckdb
     threads: 12
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: adventureworks
      schema: dbo
      threads: 12

    clickhouse:
      type: clickhouse
      host: localhost
      user: default
      port: 8123
      dbname: adventureworks
      schema: adventureworks
      threads: 10